prop:
  upload-folder: E:/test/
# 配置SpringMVC文件上传限制，默认1M。注意MB要大写，不然报错。SpringBoot版本不同，配置项不同
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  datasource:
    url: jdbc:mysql://localhost/db_big_pro_javaee
    username: root
    password: 18487997
    driver-class-name: com.mysql.cj.jdbc.Driver